### ISSUE TITLE
[ChunkyMap] Rendering tile failed

### ISSUE THREAD

**Issue by ailmanki** [leMaik/ChunkyMap#30]
Happens from time to time with cloud rendering enabled:

```
[19:05:29 WARN]: [ChunkyMap] Rendering tile failed
java.util.ConcurrentModificationException: null
at java.util.HashMap.computeIfAbsent(HashMap.java:1134) ~[?:?]
at net.minecraft.server.v1_16_R3.Convertable$ConversionSession.getWorldFolder(Convertable.java:226) ~[patched_1.16.5.jar:git-Paper-547]
at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.getWorldFolder(CraftWorld.java:2099) ~[patched_1.16.5.jar:git-Paper-547]
at de.lemaik.chunkymap.dynmap.ChunkyMapTile.lambda$render$5(ChunkyMapTile.java:76) ~[?:?]
at de.lemaik.chunkymap.rendering.rs.RemoteRenderer.render(RemoteRenderer.java:47) ~[?:?]
at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:74) ~[?:?]
at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:804) ~[?:?]
at org.dynmap.MapManager$FullWorldRenderState.access$1300(MapManager.java:262) ~[?:?]
at org.dynmap.MapManager$FullWorldRenderState$3.call(MapManager.java:686) ~[?:?]
at org.dynmap.MapManager$FullWorldRenderState$3.call(MapManager.java:684) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by leMaik** [comment]
Probably happens in Java 9+ only due to https://bugs.openjdk.java.net/browse/JDK-8071667 being fixed. This will be fixed in 2.6.0-pre3.
