### ISSUE TITLE
ChunkyMap Loading & Rendering Issue

### ISSUE THREAD

**Issue by MrKorvic** [leMaik/ChunkyMap#33]
Updated to ChunkyMap 2.6.0 pre2 and on-load I receive this error;

```[10:01:37 WARN]: [ChunkyMap] Loaded class org.dynmap.hdmap.HDMap from dynmap v3.1-457 which is not a depend, softdepend or loadbefore of this plugin.
>.... [10:01:37 INFO]: Warning: Could not load settings from /home/container/?/.chunky/chunky.json - defaults will be used
>.... [10:01:37 INFO]: java.io.FileNotFoundException: ?/.chunky/chunky.json (No such file or directory)
>.... [10:01:37 INFO]: at java.io.FileInputStream.open0(Native Method)
>.... [10:01:37 INFO]: at java.io.FileInputStream.open(FileInputStream.java:195)
>.... [10:01:37 INFO]: at java.io.FileInputStream.<init>(FileInputStream.java:138)
>.... [10:01:37 INFO]: at se.llbit.chunky.JsonSettings.load(JsonSettings.java:54)
>.... [10:01:37 INFO]: at se.llbit.chunky.PersistentSettings.changeSettingsDirectory(PersistentSettings.java:414)
>.... [10:01:37 INFO]: at se.llbit.chunky.PersistentSettings.<clinit>(PersistentSettings.java:86)
>.... [10:01:37 INFO]: at de.lemaik.chunkymap.rendering.local.ChunkyRenderer.<init>(ChunkyRenderer.java:60)
>.... [10:01:37 INFO]: at de.lemaik.chunkymap.dynmap.ChunkyMap.<init>(ChunkyMap.java:69)
>.... [10:01:37 INFO]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>.... [10:01:37 INFO]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>.... [10:01:37 INFO]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>.... [10:01:37 INFO]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>.... [10:01:37 INFO]: at org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:341)
>.... [10:01:37 INFO]: at org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:355)
>.... [10:01:37 INFO]: at org.dynmap.DynmapWorld.loadConfiguration(DynmapWorld.java:345)
>.... [10:01:37 INFO]: at org.dynmap.MapManager.activateWorld(MapManager.java:1352)
>.... [10:01:37 INFO]: at org.dynmap.DynmapCore.processWorldLoad(DynmapCore.java:2124)
>.... [10:01:37 INFO]: at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:978)
>.... [10:01:37 INFO]: at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:946)
>.... [10:01:37 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
>.... [10:01:37 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
>.... [10:01:37 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
>.... [10:01:37 INFO]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
>.... [10:01:37 INFO]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
>.... [10:01:37 INFO]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580)
>.... [10:01:37 INFO]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280)
>.... [10:01:37 INFO]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055)
>.... [10:01:37 INFO]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
>.... [10:01:37 INFO]: at java.lang.Thread.run(Thread.java:748)```

**Comment by leMaik** [comment]
The warnings in 2.6.0-pre2 are just warnings, you can ignore them (will be gone in 2.6.0-pre3).

The error in 2.5.2 is a chunky bug I'll have to look into. The chunky version used by 2.4.2 doesn't fetch skull textures so that's why it works I guess.

**Comment by leMaik** [comment]
@MrKorvic I can't reproduce this issue and I don't understand how this could happen from the stack trace. If this still happens… can you send me your world (maybe if you can narrow down the area where this happens)? I'd really like to fix this bug.

**Comment by MrKorvic** [comment]
> @MrKorvic I can't reproduce this issue and I don't understand how this could happen from the stack trace. If this still happens… can you send me your world (maybe if you can narrow down the area where this happens)? I'd really like to fix this bug.

For the time being, we're sticking to the lower version so that our dynmap will function. If you'd like a copy of any data feel free to contact me on Discord `Korvic#9999` and I'll do what I can to help out.

**Comment by leMaik** [comment]
Sent you a friend request. :+1: Great that you found a workaround but I'd still like to fix it. ;-)

**Comment by leMaik** [comment]
This issue is fixed in Chunky 2.4.0 and will be fixed here in the next release.
