### ISSUE TITLE
Getting an error when starting server and some newer blocks are rendering as "?"

### ISSUE THREAD

**Issue by marcucio** [leMaik/ChunkyMap#39]
I get the following message when my server starts and also the newer 1.17 blocks are getting rendered as "?".  Not sure if something is off with my settings or if chunkymap does not fully support 1.17.1

```
java.util.ConcurrentModificationException: null
at java.util.HashMap.computeIfAbsent(HashMap.java:1225) ~[?:?]
at net.minecraft.world.level.storage.Convertable$ConversionSession.getWorldFolder(Convertable.java:349) ~[spigot-1.17.1.jar:3187-Spigot-d03d7f1-b8c522d]
at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getWorldFolder(CraftWorld.java:1929) ~[spigot-1.17.1.jar:3187-Spigot-d03d7f1-b8c522d]
at de.lemaik.chunkymap.dynmap.ChunkyMapTile.lambda$render$2(ChunkyMapTile.java:69) ~[ChunkyMap-2.5.2.jar:?]
at de.lemaik.chunkymap.rendering.local.ChunkyRenderer.render(ChunkyRenderer.java:98) ~[ChunkyMap-2.5.2.jar:?]
at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:67) [ChunkyMap-2.5.2.jar:?]
at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:789) [Dynmap-3.2-beta-2-spigot.jar:?]
at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:720) [Dynmap-3.2-beta-2-spigot.jar:?]
at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) [Dynmap-3.2-beta-2-spigot.jar:?]
at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) [Dynmap-3.2-beta-2-spigot.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by leMaik** [comment]
1.17 will be supported in the next version (that will use Chunky 2.4.0), the error above too. :) I have no ETA for a release, but... Soon

**Comment by marcucio** [comment]
Is this a big change to support 1.17? If this something I can easily build myslef?

**Comment by leMaik** [comment]
See #43 or #46, ie. the chunky-2.4 branch supports 1.19 and a new pre-release will be published soon.
