### ISSUE TITLE
Upcoming Dynmap API change for version 3.2

### ISSUE THREAD

**Issue by ShirleyNekoDev** [leMaik/ChunkyMap#40]
Dynmap changed its MapStorageTile::write definition which now includes a timstamp - see:
https://github.com/webbukkit/dynmap/commit/476aa0c133fcb149f90fe4b5f165f76bba404019#diff-3630f18b1c9c92d9e49d2c8fb2182a7b8e560f84d590c91de578ef495322a1c2

```
[19:49:02 WARN]: [ChunkyMap] Rendering tile failed
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'boolean org.dynmap.storage.MapStorageTile.write(long, java.awt.image.BufferedImage)'
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069) ~[?:?]
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:191) [ChunkyMap-2.5.2-patched.jar:?]
        at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:804) [Dynmap-3.2-beta-3-spigot.jar:?]
        at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:694) [Dynmap-3.2-beta-3-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) [Dynmap-3.2-beta-3-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) [Dynmap-3.2-beta-3-spigot.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.dynmap.storage.MapStorageTile.write(long, java.awt.image.BufferedImage)'
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.lambda$render$5(ChunkyMapTile.java:183) ~[ChunkyMap-2.5.2-patched.jar:?]        at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2164) ~[?:?]
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:176) ~[ChunkyMap-2.5.2-patched.jar:?]
        ... 10 more
```
Found in Dynmap version: 3.2-beta-3

**Comment by plytki** [comment]
Same issue.






































**oj tak tak byczq +1**
