### ISSUE TITLE
Rendering tile failed

### ISSUE THREAD

**Issue by simsnet** [leMaik/ChunkyMap#41]
Tried to render using the example in the readme but got this error:

Version: Paper 1.17.1 build 381
Dynmap version: 3.2.1-531

```
13.11 19:41:18 [Server] WARN Rendering tile failed
13.11 19:41:18 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'boolean org.dynmap.storage.MapStorageTile.write(long, java.awt.image.BufferedImage)'
13.11 19:41:18 [Server] INFO at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
13.11 19:41:18 [Server] INFO at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069) ~[?:?]
13.11 19:41:18 [Server] INFO at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:99) ~[ChunkyMap-2.5.2.jar:?]
13.11 19:41:18 [Server] INFO at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:804) ~[Dynmap-3.2.1-spigot.jar:?]
13.11 19:41:18 [Server] INFO at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:720) ~[Dynmap-3.2.1-spigot.jar:?]
13.11 19:41:18 [Server] INFO at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) ~[Dynmap-3.2.1-spigot.jar:?]
13.11 19:41:18 [Server] INFO at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) ~[Dynmap-3.2.1-spigot.jar:?]
13.11 19:41:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
13.11 19:41:18 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
13.11 19:41:18 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
13.11 19:41:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
13.11 19:41:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
13.11 19:41:18 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
13.11 19:41:18 [Server] INFO Caused by: java.lang.NoSuchMethodError: 'boolean org.dynmap.storage.MapStorageTile.write(long, java.awt.image.BufferedImage)'
13.11 19:41:18 [Server] INFO at de.lemaik.chunkymap.dynmap.ChunkyMapTile.lambda$render$3(ChunkyMapTile.java:92) ~[ChunkyMap-2.5.2.jar:?]
13.11 19:41:18 [Server] INFO at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) ~[?:?]
13.11 19:41:18 [Server] INFO at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) ~[?:?]
13.11 19:41:18 [Server] INFO at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2164) ~[?:?]
13.11 19:41:18 [Server] INFO at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:87) ~[ChunkyMap-2.5.2.jar:?]
13.11 19:41:18 [Server] INFO ... 10 more
```

**Comment by Marvosg** [comment]
Same issue here, my log:

```
[02:49:55 INFO]: [ChunkyMap] Enabling ChunkyMap v2.5.2*
[02:49:55 INFO]: [dynmap] Enabling dynmap v3.2.1-531
[02:49:56 INFO]: [dynmap] Added 2 custom biome mappings
[02:49:56 INFO]: [dynmap] Using Bukkit Permissions (superperms) for access control
[02:49:56 INFO]: [dynmap] Web interface permissions only available for online users
[02:49:56 INFO]: [dynmap] Mod Support processing completed
[02:49:57 INFO]: [dynmap] Loaded 25 shaders.
[02:49:57 INFO]: [dynmap] Loaded 83 perspectives.
[02:49:57 INFO]: [dynmap] Loaded 22 lightings.
[02:49:57 INFO]: [dynmap] Starting enter/exit processing
[02:49:57 INFO]: [dynmap] Finish marker initialization
[02:49:58 INFO]: [dynmap] Web server started on address 0.0.0.0:25585
[02:49:58 INFO]: [dynmap] version 3.2.1-531 is enabled - core version 3.2.1-531
[02:49:58 INFO]: [dynmap] For support, visit https://reddit.com/r/Dynmap or our Discord at https://discord.gg/s3rd5qn
[02:49:58 INFO]: [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
[02:49:58 INFO]: [dynmap] If you'd like to donate, please visit https://www.patreon.com/dynmap or https://ko-fi.com/michaelprimm
[02:49:58 WARN]: [ChunkyMap] Loaded class org.dynmap.hdmap.HDMap from dynmap v3.2.1-531 which is not a depend, softdepend or loadbefore of this plugin.
[02:49:58 INFO]: [ChunkyMap] [STDOUT] Warning: Could not load settings from /home/container/.chunky/chunky.json - defaults will be used
[02:49:58 WARN]: Nag author(s): '[]' of 'ChunkyMap' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[02:49:58 INFO]: [ChunkyMap] [STDOUT] Warning: Could not load settings from /home/container/plugins/ChunkyMap/chunky/chunky.json - defaults will be used
[02:49:58 WARN]: Nag author(s): '[]' of 'ChunkyMap' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[02:49:58 INFO]: [ChunkyMap] [STDOUT] Warning: Chunky settings directory does not exist. Creating settings directory at /home/container/plugins/ChunkyMap/chunky
[02:49:58 WARN]: Nag author(s): '[]' of 'ChunkyMap' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[02:49:58 INFO]: [ChunkyMap] Downloading additional textures for Minecraft 1.16.2
[02:50:01 WARN]: [ChunkyMap] You didn't specify a texturepack for a map that is rendered with Chunky. The Minecraft 1.16.2 textures will be used.
[02:50:02 ERROR]: [ChunkyMap] [STDERR] Minecraft Jar not found: falling back on placeholder textures.
[02:50:02 WARN]: Nag author(s): '[]' of 'ChunkyMap' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[02:50:03 ERROR]: [ChunkyMap] [STDERR] Minecraft Jar not found: falling back on placeholder textures.
[02:50:03 WARN]: Nag author(s): '[]' of 'ChunkyMap' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[02:50:03 INFO]: [dynmap] Loaded 4 maps of world 'world'.
[02:50:03 INFO]: [dynmap] Loaded 63598 pending tile renders for world 'world'
[02:50:03 INFO]: [dynmap] Loaded 2 maps of world 'world_nether'.
[02:50:03 INFO]: [dynmap] Loaded 2 maps of world 'world_the_end'.
[02:50:03 INFO]: [dynmap] Enabled
[02:50:03 INFO]: Starting GS4 status listener
[02:50:03 INFO]: Thread Query Listener started
[02:50:03 INFO]: Query running on 0.0.0.0:25580
[02:50:03 INFO]: Running delayed init tasks
[02:50:03 INFO]: Done (30.252s)! For help, type "help"
game@DSH~ Server marked as running...
[02:50:03 INFO]: Timings Reset
[02:50:03 INFO]: [dynmap] Loading default resource pack
[02:50:38 WARN]: [ChunkyMap] Rendering tile failed
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'boolean org.dynmap.storage.MapStorageTile.write(long, java.awt.image.BufferedImage)'
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069) ~[?:?]
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:99) [ChunkyMap-2.5.2.jar:?]
        at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:789) [Dynmap-3.2.1-spigot.jar:?]
        at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:720) [Dynmap-3.2.1-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) [Dynmap-3.2.1-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) [Dynmap-3.2.1-spigot.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.dynmap.storage.MapStorageTile.write(long, java.awt.image.BufferedImage)'
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.lambda$render$3(ChunkyMapTile.java:92) ~[ChunkyMap-2.5.2.jar:?]
        at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2164) ~[?:?]
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:87) ~[ChunkyMap-2.5.2.jar:?]
        ... 10 more
```

**Comment by leMaik** [comment]
For DynMap 3.2, you need ChunkyMap [v2.6.0-pre3](https://github.com/leMaik/ChunkyMap/releases/tag/v2.6.0-pre3) or later. Updating it will fix the issue.
