### ISSUE TITLE
(1.18 issue) NoSuchMethodError: 'boolean org.dynmap.storage.MapStorageTile.write(long, java.awt.image.BufferedImage)'

### ISSUE THREAD

**Issue by bananasmoothii** [leMaik/ChunkyMap#43]
I can't render any map, I'm getting 
```
23.12 20:10:57 [Server] INFO Full render starting on world 'world'...
23.12 20:11:05 [Server]  [ChunkyMap] Rendering tile failed
23.12 20:11:05 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'boolean org.dynmap.storage.MapStorageTile.write(long, java.awt.image.BufferedImage)'
23.12 20:11:05 [Server] INFO at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
23.12 20:11:05 [Server] INFO at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
23.12 20:11:05 [Server] INFO at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:99) ~[ChunkyMap-2.5.2.jar:?]
23.12 20:11:05 [Server] INFO at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:804) ~[Dynmap-3.3-beta-3-spigot.jar:?]
23.12 20:11:05 [Server] INFO at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:720) ~[Dynmap-3.3-beta-3-spigot.jar:?]
23.12 20:11:05 [Server] INFO at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) ~[Dynmap-3.3-beta-3-spigot.jar:?]
23.12 20:11:05 [Server] INFO at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) ~[Dynmap-3.3-beta-3-spigot.jar:?]
23.12 20:11:05 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
23.12 20:11:05 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
23.12 20:11:05 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
23.12 20:11:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
23.12 20:11:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
23.12 20:11:05 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
23.12 20:11:05 [Server] INFO Caused by: java.lang.NoSuchMethodError: 'boolean org.dynmap.storage.MapStorageTile.write(long, java.awt.image.BufferedImage)'
23.12 20:11:05 [Server] INFO at de.lemaik.chunkymap.dynmap.ChunkyMapTile.lambda$render$3(ChunkyMapTile.java:92) ~[ChunkyMap-2.5.2.jar:?]
23.12 20:11:05 [Server] INFO at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
23.12 20:11:05 [Server] INFO at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
23.12 20:11:05 [Server] INFO at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
```

Paper version git-Paper-"464b171" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
dynmap version 3.3-beta-3-591
ChunkyMap version 2.5.2

**Comment by leMaik** [comment]
Please try [v2.6.0-pre3](https://github.com/leMaik/ChunkyMap/releases/tag/v2.6.0-pre3) or later, which supports Dynmap 3.2 or later.

It doesn't support Minecraft 1.18 yet, though. I'll have to update to Chunky 2.4.x, but first backport 1.18 support to Chunky 2.4.x in order to support that 1.18 worlds.

**Comment by bananasmoothii** [comment]
Oh ok. I'm on 1.18 so I'll have to wait then :upside_down_face:

**Comment by leMaik** [comment]
I'll just leave this issue open until we have 1.18 support.

**Comment by leMaik** [comment]
The chunky-2.4 branch now supports 1.19 and the latest dynmap version. A new pre-release will be published soon.
