### ISSUE TITLE
1.19 support?

### ISSUE THREAD

**Issue by ghost** [leMaik/ChunkyMap#46]
Hi, by any chance will there be 1.19 support for this? I would love to see it on the latest version, and as of now the plugin works on 1.19.2 but it's buggy. (I've manually built this plugin using Maven with the Chunky 2.4 branch)

As of now, I've been getting a lot of errors about tile rendering failure and missing header in region files.
I hope the development continues, this plugin is amazing :)

**Comment by TYX7601** [comment]
I also forgot to mention that it's also been giving me a lot of NullPointerException:null errors. I hope this helps.

**Comment by Dantevg** [comment]
I also tried to get it working on 1.19 with the chunky-2.4 branch and got the same errors. This is the specific stack-trace for the NullPointerExceptions:
```
java.lang.NullPointerException: Cannot invoke "se.llbit.chunky.chunk.ChunkData.getBiomeData()" because "chunkData" is null
        at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:1030) ~[ChunkyMap-2.6.0-pre3-jar-with-dependencies.jar:?]
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.lambda$render$6(ChunkyMapTile.java:142) ~[ChunkyMap-2.6.0-pre3-jar-with-dependencies.jar:?]
        at de.lemaik.chunkymap.rendering.local.ChunkyRenderer.render(ChunkyRenderer.java:109) ~[ChunkyMap-2.6.0-pre3-jar-with-dependencies.jar:?]
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:69) ~[ChunkyMap-2.6.0-pre3-jar-with-dependencies.jar:?]
        at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:810) ~[Dynmap-3.4-spigot.jar:?]
        at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:726) ~[Dynmap-3.4-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:234) ~[Dynmap-3.4-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:252) ~[Dynmap-3.4-spigot.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Dantevg** [comment]
Not OP, but I believe I used chunky from the installer (not the remove-static-registries branch because I couldn't get it to compile).
But, I only got these errors at the very start and I personally haven't seen these errors occur since.

**Comment by leMaik** [comment]
The recommended (and tested) Chunky snapshot is in the `pom.xml` file and maven should get it automatically from my repo.

**Comment by Dantevg** [comment]
Ah, I see. I followed [the readme](https://github.com/leMaik/ChunkyMap/tree/chunky-2.4#building-chunkymap), didn't know that was not necessary. I just recompiled it and I'm getting the same errors on a blank world / server. My exact steps:
- Create new blank server with `paper-1.19.2-197.jar`. (the latest `spigot-1.19.2.jar` yields the same results, but takes so much longer to initialise)
- Place `ChunkyMap-2.6.0-pre3-jar-with-dependencies.jar` and `Dynmap-3.4-spigot.jar` in plugins folder. (run server to generate dynmap config files)
- Place the following in `plugins/dynmap/worlds.txt` and restart server.
  ```yml
  worlds:
    - name: world
      maps:
        - class: de.lemaik.chunkymap.dynmap.ChunkyMap
          name: chunky_se
          title: "Chunky SE"
          perspective: iso_SE_30_hires
  ```
- Execute `/dynmap radiusrender world 0 0 64`
- Wait 1 to 2 minutes before getting error:  
  `[18:27:13 WARN]: [ChunkyMap] Rendering tile 24_-1 failed`
  (directly followed by NullPointerException as above)

Exact Dynmap version: `v3.4-828`

Java version:
```
java version "18.0.2" 2022-07-19
Java(TM) SE Runtime Environment (build 18.0.2+9-61)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)
```

**Comment by leMaik** [comment]
Try this build and please report any bugs you see! :pray: 
https://github.com/leMaik/ChunkyMap/releases/tag/v2.6.0-pre4

**Comment by Dantevg** [comment]
I don't see any errors anymore, so it seems to be all good!

**Comment by TMUniversal** [comment]
Using `2.6.0-pre4` (have not tested other versions) on 1.19.2 (`git-Purpur-1858 (MC: 1.19.2)`), I get only blank images. Have I misconfigured something?

```yaml
    -   class: de.lemaik.chunkymap.dynmap.ChunkyMap
        chunkyThreads: 4
        name: surface
        title: Surface
        perspective: iso_SE_30_hires
        prefix: t
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1
        mapzoomout: 3
        boostzoom: 2
```
