### ISSUE TITLE
Rendering tile failed, and denoising issue

### ISSUE THREAD

**Issue by Cloudeveloper** [leMaik/ChunkyMap#48]
I had multiple warns stating that rendering a tile has failed, I am running ChunkyMap 2.60-pre4 on Minecraft 1.19.3 on a virtual ubuntu server, here are what they say:
1st:
`[16:54:44 WARN]: [ChunkyMap] Rendering tile 4_11 failed
java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because the return value of "se.llbit.chunky.world.World.getWorldDirectory()" is null
        at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:888) ~[ChunkyMap-2.6.0-pre4.jar:?]
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.lambda$render$6(ChunkyMapTile.java:142) ~[ChunkyMap-2.6.0-pre4.jar:?]
        at de.lemaik.chunkymap.rendering.local.ChunkyRenderer.render(ChunkyRenderer.java:109) ~[ChunkyMap-2.6.0-pre4.jar:?]
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:69) ~[ChunkyMap-2.6.0-pre4.jar:?]
        at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:810) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:726) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:234) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:252) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]`

2nd:
`[16:56:10 WARN]: [ChunkyMap] Rendering tile 9_8 failed
java.lang.NullPointerException: null`
This results in more than half of the tiles needing to be rendered to be blank

The denoising issue oversaturated the map, causing most blocks to look very blue on the top of the block, I can render a quick image if requested.

**Comment by Cloudeveloper** [comment]
Update: This is a linux only update, but it'll be great to have chunkymap compatible with linux operating systems

**Comment by leMaik** [comment]
This is odd, I've never used ChunkyMap on a OS _other_ than Linux. :sweat_smile: 

Is there anything special about how and where your world is stored? Apparently Bukkit returns `null` for the world directory. :thinking:

**Comment by Vexicle** [comment]
I can't check right now, but I think the place where it stores the tiles is default, I'll reply to this again if I have access to my computer again.
