### ISSUE TITLE
error loading chunck

### ISSUE THREAD

**Issue by Timtaran** [leMaik/ChunkyMap#49]
```
[18:47:22 WARN]: [ChunkyMap] Rendering tile 228_-71 failed
java.lang.RuntimeException: java.lang.NullPointerException
        at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:1004) ~[?:?]
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.lambda$render$6(ChunkyMapTile.java:142) ~[?:?]
        at de.lemaik.chunkymap.rendering.local.ChunkyRenderer.render(ChunkyRenderer.java:109) ~[?:?]
        at de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:69) ~[?:?]
        at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:810) ~[?:?]
        at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:726) ~[?:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:234) ~[?:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:252) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NullPointerException
```

**Comment by leMaik** [comment]
Unfortunately, I can't debug this. We need the stack trace of the `NullPointerException`.
